### ISSUE TITLE
Some examples segfault on MacOS

### ISSUE THREAD

**Issue by lamech** [thomas-maeder/popeye#355]
I built v4.87 from source on my MacBook Pro M2 using ideas suggested in #304. The resulting binary handles a lot of things quite well, but notably produces segmentation faults on the following inputs when I run `scripts/solveExamples.sh`:

```
EXAMPLES/blackchk.inp
EXAMPLES/extragrid.inp
EXAMPLES/proteanp.inp
EXAMPLES/sat.inp
BEISPIEL/maxi.inp
BEISPIEL/nontriv.inp
BEISPIEL/sat.inp
BEISPIEL/stip.inp
```

I see the same segmentation faults if I use the v4.85 build from #304.

If I load an Ubuntu Dockerfile and build a Linux v4.87 for aarch64 inside the container, everything works fine and I do not see these segmentation faults.

Full output and Dockerfile.txt attached (I can't use `Dockerfile` because Github won't let me attach a file with no extension). Assuming one has Docker installed, one can build and run the Dockerfile with:

```
docker build -f Dockerfile.txt -t popeye-chess:latest .       # Build the Docker image
docker run -it --entrypoint /bin/bash popeye-chess            # Open a shell on the container
cd popeye && py EXAMPLES/blackchk.inp                         # Quick test, should not segfault
```

[solveExamples-output.zip](https://github.com/thomas-maeder/popeye/files/12063238/solveExamples-output.zip)
[Dockerfile.txt](https://github.com/thomas-maeder/popeye/files/12063259/Dockerfile.txt)

**Comment by lamech** [comment]
Further, testing my native MacOS build with [LeakSanitizer](https://clang.llvm.org/docs/LeakSanitizer.html) I see:

```
popeye EXAMPLES/blackchk.inp
Popeye Darwin-21.6.0-arm-64Bit v4.87 (1024 MB)
takes 13 min on Athlon 2400 / 200MB

              C.Poisson
         The Problemist 2001

+---a---b---c---d---e---f---g---h---+
|                                   |
8   .   .   .   .  -K   .   .   .   8
|                                   |
7   K   .   .   .  -P   .   .  -P   7
|                                   |
6   .   .   .   .   .   .   .   .   6
|                                   |
5   .   .   .   .   .   .   .   .   5
|                                   |
4   .   .   .   .   .   .   .   .   4
|                                   |
3   .   .   .   .   .   .   .   .   3
|                                   |
2   .   .   .   .   .   .   .   .   2
|                                   |
1   .   .   .   .   .   .   .   .   1
|                                   |
+---a---b---c---d---e---f---g---h---+
  s#31                        1 + 3
             BlackChecks
AddressSanitizer:DEADLYSIGNAL
=================================================================
==98220==ERROR: AddressSanitizer: stack-overflow on address 0x00016cf559a0 (pc 0x0001027220a0 bp 0x00016cf7e290 sp 0x00016cf55980 T0)
    #0 0x1027220a0 in optimise_final_moves_move_generator remove_non_reachers.c:103
    #1 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #2 0x10286871c in stip_traverse_moves_dead_end moves_traversal.c:259
    #3 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #4 0x102867894 in stip_traverse_moves_ready_for_defense moves_traversal.c:134
    #5 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #6 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #7 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #8 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #9 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #10 0x1028682c8 in stip_traverse_moves_move_played moves_traversal.c:227
    #11 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #12 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #13 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #14 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #15 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #16 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #17 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #18 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #19 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #20 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #21 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #22 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #23 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #24 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #25 0x10272218c in optimise_final_moves_move_generator remove_non_reachers.c:113
    #26 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #27 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #28 0x10286871c in stip_traverse_moves_dead_end moves_traversal.c:259
    #29 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #30 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #31 0x102867700 in stip_traverse_moves_ready_for_attack moves_traversal.c:119
    #32 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #33 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #34 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #35 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #36 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #37 0x1028682c8 in stip_traverse_moves_move_played moves_traversal.c:227
    #38 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #39 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #40 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #41 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #42 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #43 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #44 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #45 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #46 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #47 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #48 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #49 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #50 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #51 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #52 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #53 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #54 0x102721d58 in generator_swallow_goal remove_non_reachers.c:183
    #55 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #56 0x10272218c in optimise_final_moves_move_generator remove_non_reachers.c:113
    #57 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #58 0x10286871c in stip_traverse_moves_dead_end moves_traversal.c:259
    #59 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #60 0x102867894 in stip_traverse_moves_ready_for_defense moves_traversal.c:134
    #61 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #62 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #63 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #64 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #65 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #66 0x1028682c8 in stip_traverse_moves_move_played moves_traversal.c:227
    #67 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #68 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #69 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #70 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #71 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #72 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #73 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #74 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #75 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #76 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #77 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #78 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #79 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #80 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #81 0x10272218c in optimise_final_moves_move_generator remove_non_reachers.c:113
    #82 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #83 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #84 0x10286871c in stip_traverse_moves_dead_end moves_traversal.c:259
    #85 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #86 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #87 0x102867700 in stip_traverse_moves_ready_for_attack moves_traversal.c:119
    #88 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #89 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #90 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #91 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #92 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #93 0x1028682c8 in stip_traverse_moves_move_played moves_traversal.c:227
    #94 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #95 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #96 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #97 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #98 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #99 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #100 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #101 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #102 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #103 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #104 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #105 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #106 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #107 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #108 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #109 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #110 0x102721d58 in generator_swallow_goal remove_non_reachers.c:183
    #111 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #112 0x10272218c in optimise_final_moves_move_generator remove_non_reachers.c:113
    #113 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #114 0x10286871c in stip_traverse_moves_dead_end moves_traversal.c:259
    #115 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #116 0x102867894 in stip_traverse_moves_ready_for_defense moves_traversal.c:134
    #117 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #118 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #119 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #120 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #121 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #122 0x1028682c8 in stip_traverse_moves_move_played moves_traversal.c:227
    #123 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #124 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #125 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #126 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #127 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #128 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #129 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #130 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #131 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #132 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #133 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #134 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #135 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #136 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #137 0x10272218c in optimise_final_moves_move_generator remove_non_reachers.c:113
    #138 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #139 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #140 0x10286871c in stip_traverse_moves_dead_end moves_traversal.c:259
    #141 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #142 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #143 0x102867700 in stip_traverse_moves_ready_for_attack moves_traversal.c:119
    #144 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #145 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #146 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #147 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #148 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #149 0x1028682c8 in stip_traverse_moves_move_played moves_traversal.c:227
    #150 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #151 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #152 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #153 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #154 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #155 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #156 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #157 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #158 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #159 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #160 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #161 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #162 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #163 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #164 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #165 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #166 0x102721d58 in generator_swallow_goal remove_non_reachers.c:183
    #167 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #168 0x10272218c in optimise_final_moves_move_generator remove_non_reachers.c:113
    #169 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #170 0x10286871c in stip_traverse_moves_dead_end moves_traversal.c:259
    #171 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #172 0x102867894 in stip_traverse_moves_ready_for_defense moves_traversal.c:134
    #173 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #174 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #175 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #176 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #177 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #178 0x1028682c8 in stip_traverse_moves_move_played moves_traversal.c:227
    #179 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #180 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #181 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #182 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #183 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #184 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #185 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #186 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #187 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #188 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #189 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #190 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #191 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #192 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #193 0x10272218c in optimise_final_moves_move_generator remove_non_reachers.c:113
    #194 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #195 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #196 0x10286871c in stip_traverse_moves_dead_end moves_traversal.c:259
    #197 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #198 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #199 0x102867700 in stip_traverse_moves_ready_for_attack moves_traversal.c:119
    #200 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #201 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #202 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #203 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #204 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #205 0x1028682c8 in stip_traverse_moves_move_played moves_traversal.c:227
    #206 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #207 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #208 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #209 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #210 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #211 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #212 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #213 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #214 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #215 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #216 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #217 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #218 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #219 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #220 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #221 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #222 0x102721d58 in generator_swallow_goal remove_non_reachers.c:183
    #223 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #224 0x10272218c in optimise_final_moves_move_generator remove_non_reachers.c:113
    #225 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #226 0x10286871c in stip_traverse_moves_dead_end moves_traversal.c:259
    #227 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #228 0x102867894 in stip_traverse_moves_ready_for_defense moves_traversal.c:134
    #229 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #230 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #231 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #232 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #233 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #234 0x1028682c8 in stip_traverse_moves_move_played moves_traversal.c:227
    #235 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #236 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #237 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #238 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #239 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #240 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #241 0x102866744 in stip_traverse_moves_binary moves_traversal.c:324
    #242 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #243 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #244 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #245 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #246 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #247 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #248 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #249 0x10272218c in optimise_final_moves_move_generator remove_non_reachers.c:113
    #250 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #251 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #252 0x10286871c in stip_traverse_moves_dead_end moves_traversal.c:259
    #253 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #254 0x102865eb4 in stip_traverse_moves_pipe moves_traversal.c:18
    #255 0x102867700 in stip_traverse_moves_ready_for_attack moves_traversal.c:119

SUMMARY: AddressSanitizer: stack-overflow remove_non_reachers.c:103 in optimise_final_moves_move_generator
==98220==ABORTING
```

**Comment by lamech** [comment]
With #359 merged, this issue can be closed.
